# pyproject.toml

[tool.black]
line-length = 88
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
  | pyproject\.toml  # Exclude pyproject.toml
  | .*\.pyc          # Exclude compiled Python files
    # Add other files or patterns to exclude
)/
'''